name: final_project_pengaduan_masyarakat_sem2
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  flutter_bloc: ^9.1.0
  freezed_annotation: ^2.0.0
  dartz: ^0.10.1
  shared_preferences: ^2.5.3
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_svg: ^2.1.0
  flutter_rating_bar: ^4.0.1
  flutter_rating_stars: ^1.1.0
  google_maps_flutter: ^2.12.1
  geocoding: ^3.0.0
  rate_my_app: ^2.3.1
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.0.0
  flutter_lints: ^4.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0

flutter_gen:
  output: lib/assets/
  line_length: 80

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/nav/
    - assets/icons/profile/
